runtime: nodejs14

instance_class: F1

env_variables:
  GOOGLE_PLACES_APIKEY: "AIzaSyC_oRYpmsi4vtq36cZuHX4AbnKR0WoIrpc"
  MONGODB_URI: "mongodb+srv://healthy-eating-app:3jlitPen3jTs4qxU@healthy-eating-app.7niarno.mongodb.net/?retryWrites=true&w=majority"
  NODE_ENV: "production"
